"use client";
import {useRef,useState} from "react";
import Link from "next/link";
import type {Article} from "@/lib/literature/types";
type Result={topic:string;remaining:number;generatedAt:string;articles:Article[];timeline:{year:number;count:number}[];sources:{pubmed:{total:number;systematicReviews:number;clinicalTrials:number}};methodology:string};
export default function Demo(){const [topic,setTopic]=useState("sleep quality medical residents");const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const busy=useRef(false);
 function remember(){try{localStorage.setItem("scholar-demo-topic",JSON.stringify({topic:result?.topic||topic.trim(),at:Date.now()}));}catch{}}
 async function search(){if(busy.current)return;busy.current=true;setLoading(true);setError("");setResult(null);try{const response=await fetch("/api/radar-demo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Busca indisponível");setResult(data);}catch(e){setError(e instanceof Error?e.message:"Busca indisponível");}finally{busy.current=false;setLoading(false);}}
 return <div className="max-w-5xl mx-auto"><p className="text-xs uppercase text-teal">Experimente sem cadastro · sem IA</p><h1 className="font-display text-4xl md:text-5xl mt-3">Sua pergunta encontra a literatura.</h1><p className="text-ink-soft mt-4 max-w-3xl">Pesquise publicações reais do PubMed nos últimos cinco anos. Veja o volume, os anos completos anteriores e até dez artigos recentes. Nenhuma resposta é gerada por IA.</p>
 <form onSubmit={e=>{e.preventDefault();void search();}} className="mt-7 bg-white border border-line rounded-2xl p-5"><label className="block text-sm font-medium">O que você gostaria de pesquisar?<input required minLength={3} maxLength={300} value={topic} onChange={e=>setTopic(e.target.value)} className="block w-full border rounded-card p-3 mt-2" /></label><div className="flex flex-wrap gap-2 mt-3">{["sleep quality medical residents","hypertension medication adherence","medical students burnout"].map(example=><button type="button" key={example} disabled={loading} onClick={()=>setTopic(example)} className="text-xs text-teal border border-teal/20 rounded-full px-3 py-2">{example}</button>)}</div><p className="text-xs text-ink-soft mt-3">Termos em inglês costumam ajudar a recuperar literatura internacional. Até três tentativas diárias por rede/IP, com reinício em UTC; redes compartilhadas podem dividir o limite. Resultados podem ser reutilizados por até uma hora.</p><button disabled={loading} className="mt-4 bg-teal text-white rounded-card px-5 py-3 disabled:opacity-50">{loading?"Consultando a literatura...":"Testar o Radar"}</button></form>
 {error&&<p role="alert" className="mt-5 bg-amber-soft rounded-card p-4 text-sm">{error} <Link href="/cadastro" onClick={remember} className="text-teal underline">Criar conta</Link></p>}
 {loading&&<p role="status" className="mt-5 text-sm">A busca pode levar alguns segundos. Estamos consultando as bases científicas.</p>}
 {result&&<section className="mt-7"><h2 className="font-display text-3xl">{result.topic}</h2><p className="text-xs text-ink-soft mt-2">Última consulta às bases: {new Date(result.generatedAt).toLocaleString("pt-BR")} · {result.remaining} tentativas restantes hoje</p><div className="grid sm:grid-cols-3 gap-4 mt-5">{[["Publicações no recorte",result.sources.pubmed.total],["Revisões sistemáticas",result.sources.pubmed.systematicReviews],["Ensaios clínicos",result.sources.pubmed.clinicalTrials]].map(([label,count])=><div key={label} className="bg-white border border-line rounded-card p-4"><p className="text-3xl">{Number(count).toLocaleString("pt-BR")}</p><p className="text-xs mt-2">{label}</p></div>)}</div><div className="bg-white border border-line rounded-2xl p-5 mt-5"><h3 className="font-medium">Publicações por ano completo</h3><div className="mt-4 space-y-3">{result.timeline.map(point=><div key={point.year} className="grid grid-cols-[45px_1fr_70px] gap-3 items-center text-sm"><span>{point.year}</span><div className="bg-paper rounded-full h-3"><div className="bg-teal h-3 rounded-full" style={{width:`${point.count/Math.max(1,...result.timeline.map(p=>p.count))*100}%`}} /></div><span>{point.count.toLocaleString("pt-BR")}</span></div>)}</div></div><h3 className="font-display text-2xl mt-7">Artigos recentes</h3>{result.articles.map(a=><article key={a.pmid||a.doi||a.title} className="mt-4 border border-line bg-white rounded-2xl p-5"><p className="text-xs text-teal">{a.year||"Ano não informado"} · {a.journal}</p><h4 className="font-display text-xl mt-2">{a.title}</h4><p className="text-xs text-ink-soft mt-2">{a.authors.slice(0,5).join(", ")}</p>{a.abstract&&<details className="mt-3 text-sm"><summary className="text-teal cursor-pointer">Ler resumo</summary><p className="leading-relaxed mt-3 text-ink-soft whitespace-pre-wrap">{a.abstract}</p></details>}{a.pubmedUrl&&<a href={a.pubmedUrl} target="_blank" rel="noreferrer" className="inline-block mt-3 text-sm text-teal underline">Consultar no PubMed</a>}</article>)}{!result.articles.length&&<p className="text-sm mt-4">Nenhum artigo com detalhes disponível neste recorte. Tente termos mais específicos ou sinônimos.</p>}<details className="mt-5 text-sm"><summary className="text-teal cursor-pointer">Como interpretar os resultados</summary><p className="text-ink-soft mt-3">{result.methodology}</p></details></section>}
 <section className="bg-ink text-white rounded-2xl p-6 mt-8"><h2 className="font-display text-3xl">Da busca ao seu projeto.</h2><p className="text-white/70 mt-3">Crie seu espaço para continuar a busca, selecionar referências, registrar a leitura e estruturar o protocolo. O tema poderá ser retomado neste navegador após o cadastro.</p><div className="flex flex-wrap gap-3 mt-5"><Link href="/cadastro" onClick={remember} className="bg-white text-ink rounded-card px-4 py-3">Criar minha conta</Link><Link href="/login" onClick={remember} className="border border-white/30 rounded-card px-4 py-3">Já tenho conta</Link></div></section></div>;
}
