import { NextResponse } from "next/server";
import { generateText, jsonSchema, Output } from "ai";
import { scholarAI, scholarAIModels, scholarAIReady, estimatedCost, providerErrorText, retryWithFallback } from "@/lib/ai/config";
import { assistantJsonSchema, assistantPrompt, isAssistantOutput, ledgerFeature, simulatedOutput, type AssistantOutput, validateAssistRequest } from "@/lib/ai/assist";
import { outputBudget } from "@/lib/ai/structured-output";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { supabaseServer } from "@/lib/supabase/server";

export const runtime = "nodejs"; export const maxDuration = 300;
const generationTimeoutMs=240_000,staleReservationMs=10*60_000;
function generationTimedOut(e:unknown){return /abort|timeout|timed out/i.test(providerErrorText(e));}
type License={id:string;status:string;mode:"simulation"|"live";starts_at:string;ends_at:string}; type Wallet={id:string;license_id:string;allowance:number;used:number;reserved:number};
async function releaseStaleReservations(userId:string){const admin=supabaseAdmin(),cutoff=new Date(Date.now()-staleReservationMs).toISOString();const {data,error}=await admin.from("scholar_usage").select("id").eq("user_id",userId).eq("status","reserved").lt("created_at",cutoff);if(error)throw error;for(const row of data||[]){const {error:settleError}=await admin.rpc("scholar_settle",{p_request:row.id,p_input:0,p_output:0,p_cost:0,p_failed:true,p_provider_id:null});if(settleError)throw settleError;}}
async function activeWallet(userId:string){await releaseStaleReservations(userId);const admin=supabaseAdmin();const {data:w,error}=await admin.from("scholar_wallets").select("id,license_id,allowance,used,reserved").eq("user_id",userId);if(error)throw error;const wallets=(w||[]) as Wallet[];if(!wallets.length)throw new Error("Sua conta ainda não possui uma franquia de assistência.");const {data:l,error:le}=await admin.from("scholar_licenses").select("id,status,mode,starts_at,ends_at").in("id",wallets.map(x=>x.license_id));if(le)throw le;const now=Date.now(),map=new Map(((l||[]) as License[]).map(x=>[x.id,x]));const found=wallets.map(wallet=>({wallet,license:map.get(wallet.license_id)})).filter(x=>x.license&&["active","trial"].includes(x.license.status)&&Date.parse(x.license.starts_at)<=now&&Date.parse(x.license.ends_at)>=now&&x.wallet.allowance-x.wallet.used-x.wallet.reserved>=scholarAI.reservedTokens).sort((a,b)=>(b.wallet.allowance-b.wallet.used-b.wallet.reserved)-(a.wallet.allowance-a.wallet.used-a.wallet.reserved))[0];if(!found)throw new Error("Franquia indisponível ou insuficiente para esta operação.");return found as {wallet:Wallet;license:License};}
function safeMessage(e:unknown){const m=providerErrorText(e)||"Não foi possível concluir a análise.";if(generationTimedOut(e))return "A análise demorou mais que o esperado e foi interrompida com segurança. Sua franquia será devolvida; tente novamente.";if(/quota|rate.?limit|resource.?exhausted|429/i.test(m))return "O limite temporário do Gemini foi atingido. Sua franquia foi devolvida; tente novamente em alguns minutos.";if(/high demand|temporar|unavailable|overloaded|503/i.test(m))return "Os modelos do Gemini estão temporariamente sobrecarregados. Sua franquia foi devolvida; tente novamente em alguns minutos.";if(/api.?key|unauthenticated|permission.?denied|forbidden|401|403/i.test(m))return "A chave do Gemini não foi aceita ou ainda não possui acesso ao modelo configurado.";if(/model.*not found|not found.*model|unsupported model|404/i.test(m))return "O modelo configurado não está disponível para este projeto do Gemini.";if(/schema|structured output|response.?format/i.test(m))return "O Gemini não aceitou o formato estruturado desta análise. Sua franquia foi devolvida.";return m.length<240?m:"Não foi possível concluir a análise agora.";}
export async function POST(request:Request){if(!scholarAIReady)return NextResponse.json({error:"A IA de teste ainda não está conectada ao Google Gemini neste ambiente."},{status:503});const client=await supabaseServer();const {data:{user}}=await client.auth.getUser();if(!user)return NextResponse.json({error:"Entre na sua conta para usar a assistência."},{status:401});let operationId:string|null=null,reserved=false;try{const input=validateAssistRequest(await request.json());const {wallet,license}=await activeWallet(user.id);const admin=supabaseAdmin();operationId=crypto.randomUUID();const model=license.mode==="simulation"?"simulation":scholarAI.model;const {error:re}=await admin.rpc("scholar_reserve",{p_request:operationId,p_wallet:wallet.id,p_user:user.id,p_feature:ledgerFeature[input.feature],p_model:model,p_tokens:scholarAI.reservedTokens,p_project:input.projectId});if(re)throw re;reserved=true;const promptVersion=`${input.feature}.v1`;const {error:ae}=await admin.from("scholar_generation_artifacts").insert({usage_id:operationId,user_id:user.id,prompt_version:promptVersion,input_snapshot:{feature:input.feature,context:input.context}});if(ae)throw ae;
if(license.mode==="simulation"){const output=simulatedOutput(input.feature);const {error:ue}=await admin.from("scholar_generation_artifacts").update({output_snapshot:output}).eq("usage_id",operationId);if(ue)throw ue;const {error:se}=await admin.rpc("scholar_settle",{p_request:operationId,p_input:0,p_output:1,p_cost:0,p_failed:false,p_provider_id:"simulation"});if(se)throw se;reserved=false;return NextResponse.json({operationId,mode:"simulation",output,usage:{inputTokens:0,outputTokens:1,costUsd:0}});}
const prompt=assistantPrompt(input.feature,input.context);let result:Awaited<ReturnType<typeof generateText>>|null=null,lastError:unknown;for(const candidate of scholarAIModels){try{result=await generateText({model:candidate.model,instructions:"Produza apoio científico responsável e rastreável para revisão humana.",maxOutputTokens:outputBudget(prompt,assistantJsonSchema,scholarAI.maxAssistOutputTokens,scholarAI.reservedTokens,1_000),maxRetries:0,abortSignal:AbortSignal.timeout(generationTimeoutMs),output:Output.object({schema:jsonSchema<AssistantOutput>(assistantJsonSchema)}),prompt});break;}catch(error){lastError=error;if(!retryWithFallback(error))throw error;}}if(!result)throw lastError||new Error("Nenhum modelo do Gemini está disponível agora.");const output=result.output as AssistantOutput,i=result.usage.inputTokens||0,o=result.usage.outputTokens||0,providerResponseId=result.response.id;
if(!isAssistantOutput(output))throw new Error("A resposta do modelo não corresponde ao formato científico esperado. Tente novamente.");if(i+o>scholarAI.reservedTokens)throw new Error("A resposta excedeu o limite de consumo da operação.");const cost=estimatedCost(i,o);const {error:ue}=await admin.from("scholar_generation_artifacts").update({output_snapshot:output}).eq("usage_id",operationId);if(ue)throw ue;const {error:se}=await admin.rpc("scholar_settle",{p_request:operationId,p_input:i,p_output:o,p_cost:cost,p_failed:false,p_provider_id:providerResponseId});if(se)throw se;reserved=false;return NextResponse.json({operationId,mode:"live",output,usage:{inputTokens:i,outputTokens:o,costUsd:cost}});
}catch(e){const timedOut=generationTimedOut(e);console.error("[scholar-ai:assist] generation failed",{operationId,model:scholarAI.model,timedOut,error:e instanceof Error?e.message:"unknown"});if(operationId&&reserved){try{const admin=supabaseAdmin();await admin.from("scholar_generation_artifacts").update({error_code:timedOut?"GENERATION_TIMEOUT":"GENERATION_FAILED"}).eq("usage_id",operationId);await admin.rpc("scholar_settle",{p_request:operationId,p_input:0,p_output:0,p_cost:0,p_failed:true,p_provider_id:null});}catch(cleanupError){console.error("[scholar-ai:assist] cleanup failed",{operationId,error:cleanupError instanceof Error?cleanupError.message:"unknown"});}}return NextResponse.json({error:safeMessage(e),operationId},{status:timedOut?504:400});}}
