import { NextResponse } from "next/server";
import { generateText, jsonSchema, Output } from "ai";
import { scholarAI, scholarAIReady, estimatedCost } from "@/lib/ai/config";
import { assistantJsonSchema, assistantPrompt, isAssistantOutput, ledgerFeature, simulatedOutput, type AssistantOutput, validateAssistRequest } from "@/lib/ai/assist";
import { outputBudget, parseValidatedJson, promptForJson } from "@/lib/ai/structured-output";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { supabaseServer } from "@/lib/supabase/server";

export const runtime = "nodejs"; export const maxDuration = 60;
type License={id:string;status:string;mode:"simulation"|"live";starts_at:string;ends_at:string}; type Wallet={id:string;license_id:string;allowance:number;used:number;reserved:number};
async function activeWallet(userId:string){const admin=supabaseAdmin();const {data:w,error}=await admin.from("scholar_wallets").select("id,license_id,allowance,used,reserved").eq("user_id",userId);if(error)throw error;const wallets=(w||[]) as Wallet[];if(!wallets.length)throw new Error("Sua conta ainda não possui uma franquia de assistência.");const {data:l,error:le}=await admin.from("scholar_licenses").select("id,status,mode,starts_at,ends_at").in("id",wallets.map(x=>x.license_id));if(le)throw le;const now=Date.now(),map=new Map(((l||[]) as License[]).map(x=>[x.id,x]));const found=wallets.map(wallet=>({wallet,license:map.get(wallet.license_id)})).filter(x=>x.license&&["active","trial"].includes(x.license.status)&&Date.parse(x.license.starts_at)<=now&&Date.parse(x.license.ends_at)>=now&&x.wallet.allowance-x.wallet.used-x.wallet.reserved>=scholarAI.reservedTokens).sort((a,b)=>(b.wallet.allowance-b.wallet.used-b.wallet.reserved)-(a.wallet.allowance-a.wallet.used-a.wallet.reserved))[0];if(!found)throw new Error("Franquia indisponível ou insuficiente para esta operação.");return found as {wallet:Wallet;license:License};}
function safeMessage(e:unknown){const m=e instanceof Error?e.message:"Não foi possível concluir a análise.";return m.length<240?m:"Não foi possível concluir a análise agora.";}
export async function POST(request:Request){if(!scholarAIReady)return NextResponse.json({error:"A assistência por IA ainda não está configurada neste ambiente."},{status:503});const client=await supabaseServer();const {data:{user}}=await client.auth.getUser();if(!user)return NextResponse.json({error:"Entre na sua conta para usar a assistência."},{status:401});let operationId:string|null=null,reserved=false;try{const input=validateAssistRequest(await request.json());const {wallet,license}=await activeWallet(user.id);const admin=supabaseAdmin();operationId=crypto.randomUUID();const model=license.mode==="simulation"?"simulation":scholarAI.model;const {error:re}=await admin.rpc("scholar_reserve",{p_request:operationId,p_wallet:wallet.id,p_user:user.id,p_feature:ledgerFeature[input.feature],p_model:model,p_tokens:scholarAI.reservedTokens,p_project:input.projectId});if(re)throw re;reserved=true;const promptVersion=`${input.feature}.v1`;const {error:ae}=await admin.from("scholar_generation_artifacts").insert({usage_id:operationId,user_id:user.id,prompt_version:promptVersion,input_snapshot:{feature:input.feature,context:input.context}});if(ae)throw ae;
if(license.mode==="simulation"){const output=simulatedOutput(input.feature);const {error:ue}=await admin.from("scholar_generation_artifacts").update({output_snapshot:output}).eq("usage_id",operationId);if(ue)throw ue;const {error:se}=await admin.rpc("scholar_settle",{p_request:operationId,p_input:0,p_output:1,p_cost:0,p_failed:false,p_provider_id:"simulation"});if(se)throw se;reserved=false;return NextResponse.json({operationId,mode:"simulation",output,usage:{inputTokens:0,outputTokens:1,costUsd:0}});}
const prompt=assistantPrompt(input.feature,input.context);const common={model:scholarAI.model,instructions:"Produza apoio científico responsável e rastreável para revisão humana.",maxOutputTokens:outputBudget(prompt,assistantJsonSchema,scholarAI.maxAssistOutputTokens,scholarAI.reservedTokens,1_000),providerOptions:{gateway:{user:user.id,tags:["scholar",input.feature,promptVersion]}}} as const;const result=scholarAI.structuredOutput==="native"?await generateText({...common,output:Output.object({schema:jsonSchema<AssistantOutput>(assistantJsonSchema)}),prompt}):await generateText({...common,prompt:promptForJson(prompt,assistantJsonSchema)});const output=scholarAI.structuredOutput==="native"?result.output as AssistantOutput:parseValidatedJson(result.text,isAssistantOutput);if(!isAssistantOutput(output))throw new Error("A resposta do modelo não corresponde ao formato científico esperado. Tente novamente.");const i=result.usage.inputTokens||0,o=result.usage.outputTokens||0;if(i+o>scholarAI.reservedTokens)throw new Error("A resposta excedeu o limite de consumo da operação.");const cost=estimatedCost(i,o);const {error:ue}=await admin.from("scholar_generation_artifacts").update({output_snapshot:output}).eq("usage_id",operationId);if(ue)throw ue;const {error:se}=await admin.rpc("scholar_settle",{p_request:operationId,p_input:i,p_output:o,p_cost:cost,p_failed:false,p_provider_id:result.response.id});if(se)throw se;reserved=false;return NextResponse.json({operationId,mode:"live",output,usage:{inputTokens:i,outputTokens:o,costUsd:cost}});
}catch(e){console.error("[scholar-ai:assist] generation failed",{operationId,model:scholarAI.model,error:e instanceof Error?e.message:"unknown"});if(operationId&&reserved){const admin=supabaseAdmin();await admin.from("scholar_generation_artifacts").update({error_code:"GENERATION_FAILED"}).eq("usage_id",operationId);await admin.rpc("scholar_settle",{p_request:operationId,p_input:0,p_output:0,p_cost:0,p_failed:true,p_provider_id:null});}return NextResponse.json({error:safeMessage(e),operationId},{status:400});}}
