"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { supabaseBrowser } from "@/lib/supabase/browser";

export type AdvisingProject={id:string;owner_id:string;title:string|null;theme:string|null;progress:number;status:string};
export type AdvisingComment={id:string;author_id:string;section_key:string;body:string;status:string;created_at:string};
export type AdvisingMeeting={id:string;created_by:string;occurred_on:string;title:string;notes:string;next_steps:string|null;created_at:string};
export type AdvisingVersion={id:string;label:string;snapshot:Record<string,unknown>;created_at:string};
export type Advisor={user_id:string;name:string|null;email:string|null;active:boolean;added_at:string};
export type AdvisorInvite={id:string;email:string|null;expires_at:string;revoked:boolean;redeemed_at:string|null};
const sections=[['general','Geral'],['question','Pergunta'],['objective','Objetivos'],['methods','Métodos'],['analysis','Análise'],['ethics','Ética'],['writing','Escrita']] as const;
const versionFields:Record<string,string>={theme:"Tema",research_question:"Pergunta",objective:"Objetivo",hypothesis:"Hipótese",study_type:"Desenho",population:"População",primary_outcome:"Desfecho",inclusion_criteria:"Inclusão",exclusion_criteria:"Exclusão",variables:"Variáveis",methods:"Métodos",analysis_plan:"Análise",ethics_notes:"Ética",manuscript_notes:"Manuscrito",status:"Status",progress:"Progresso"};

export default function AdvisingWorkspace({userId,project,comments,meetings,versions,advisors,invites,isOwner}:{userId:string;project:AdvisingProject|null;comments:AdvisingComment[];meetings:AdvisingMeeting[];versions:AdvisingVersion[];advisors:Advisor[];invites:AdvisorInvite[];isOwner:boolean}) {
  const router=useRouter();const [pending,startTransition]=useTransition();const [message,setMessage]=useState("");const [code,setCode]=useState("");const [createdCode,setCreatedCode]=useState("");
  const [inviteEmail,setInviteEmail]=useState("");const [section,setSection]=useState("general");const [comment,setComment]=useState("");
  const [meeting,setMeeting]=useState({date:new Date().toISOString().slice(0,10),title:"",notes:"",next:""});const [versionLabel,setVersionLabel]=useState("");const [compare,setCompare]=useState<string[]>([]);
  function run(action:()=>Promise<void>){setMessage("");startTransition(async()=>{try{await action();}catch(error){setMessage((error as {message?:string})?.message||"Não foi possível concluir a ação.");}});}
  async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await supabaseBrowser().rpc(name,args);if(error)throw error;return data;}
  function refresh(success:string){setMessage(success);router.refresh();}
  async function redeem(){const id=await rpc("scholar_redeem_advisor_invite",{p_code:code});setCode("");setMessage("Convite aceito. Abrindo o projeto compartilhado...");router.push(`/orientacao?projeto=${id}`);router.refresh();}
  async function createInvite(){if(!project)return;const result=await rpc("scholar_create_advisor_invite",{p_project:project.id,p_email:inviteEmail||null});setCreatedCode(String(result));setMessage("Convite criado. Copie o código; ele não será exibido novamente depois de sair desta tela.");router.refresh();}
  async function addComment(){if(!project)return;const {error}=await supabaseBrowser().from("scholar_project_comments").insert({project_id:project.id,author_id:userId,section_key:section,body:comment.trim()});if(error)throw error;setComment("");refresh("Comentário registrado.");}
  async function resolve(id:string,resolved:boolean){await rpc("scholar_resolve_project_comment",{p_comment:id,p_resolved:resolved});refresh(resolved?"Pendência resolvida.":"Comentário reaberto.");}
  async function addMeeting(){if(!project)return;const {error}=await supabaseBrowser().from("scholar_advisor_meetings").insert({project_id:project.id,created_by:userId,occurred_on:meeting.date,title:meeting.title.trim(),notes:meeting.notes.trim(),next_steps:meeting.next.trim()||null});if(error)throw error;setMeeting(current=>({...current,title:"",notes:"",next:""}));refresh("Registro da reunião salvo.");}
  async function createVersion(){if(!project)return;await rpc("scholar_create_project_version",{p_project:project.id,p_label:versionLabel});setVersionLabel("");refresh("Versão do projeto registrada.");}
  async function revoke(advisor:string){if(!project||!window.confirm("Retirar o acesso deste orientador? Os registros anteriores serão preservados."))return;await rpc("scholar_revoke_advisor",{p_project:project.id,p_user:advisor});refresh("Acesso do orientador retirado.");}
  const differences=useMemo(()=>{if(compare.length!==2)return[];const first=versions.find(v=>v.id===compare[0]);const second=versions.find(v=>v.id===compare[1]);if(!first||!second)return[];return Object.keys(versionFields).filter(key=>String(first.snapshot[key]??"")!==String(second.snapshot[key]??"")).map(key=>({label:versionFields[key],before:String(first.snapshot[key]??"A definir"),after:String(second.snapshot[key]??"A definir")}));},[compare,versions]);
  return <>
    <section className="bg-white border border-line rounded-2xl p-5 mt-6"><h2 className="font-display text-2xl">Recebeu um convite de orientação?</h2><form onSubmit={event=>{event.preventDefault();run(redeem);}} className="flex flex-col sm:flex-row gap-3 mt-4"><input required maxLength={64} value={code} onChange={event=>setCode(event.target.value)} placeholder="Cole o código recebido" className="border border-line rounded-card p-3 flex-1"/><button disabled={pending} className="bg-teal text-white rounded-card px-5 py-3 disabled:opacity-50">Aceitar convite</button></form></section>
    {!project?<section className="bg-teal-soft border border-teal/20 rounded-2xl p-6 mt-6"><h2 className="font-display text-2xl">Nenhum projeto em orientação.</h2><p className="text-sm text-ink-soft mt-3">Crie um projeto ou aceite um convite para começar.</p></section>:<>
      <section className="bg-ink text-white rounded-2xl p-6 mt-6"><p className="text-xs uppercase tracking-widest text-teal-soft">{isOwner?"Projeto sob sua gestão":"Projeto compartilhado com você"}</p><h2 className="font-display text-3xl mt-3">{project.title||project.theme||"Projeto sem título"}</h2><div className="flex gap-4 text-sm text-white/70 mt-4"><span>{project.progress}% preenchido</span><span>{comments.filter(item=>item.status==="open").length} comentários abertos</span><span>{versions.length} versões</span></div></section>
      {isOwner?<section className="bg-white border border-line rounded-2xl p-5 mt-6"><h2 className="font-display text-2xl">Convidar orientador</h2><p className="text-sm text-ink-soft mt-2">O acesso vale somente para este projeto e pode ser retirado a qualquer momento. O orientador poderá ler o protocolo e participar deste espaço de orientação; biblioteca e ideias pessoais permanecem privadas.</p><div className="flex flex-col sm:flex-row gap-3 mt-4"><input type="email" maxLength={320} value={inviteEmail} onChange={event=>setInviteEmail(event.target.value)} placeholder="E-mail do orientador (opcional)" className="border border-line rounded-card p-3 flex-1"/><button type="button" disabled={pending} onClick={()=>run(createInvite)} className="border border-teal/30 text-teal rounded-card px-4 py-3">Gerar código</button></div>{createdCode?<label className="block text-sm mt-4">Código para compartilhar<input readOnly value={createdCode} onFocus={event=>event.target.select()} className="block w-full mt-2 border rounded-card p-3 font-mono"/></label>:null}<div className="space-y-3 mt-5">{advisors.filter(item=>item.active).map(advisor=><div key={advisor.user_id} className="flex flex-wrap justify-between gap-3 border border-line rounded-card p-3"><div><p className="font-medium">{advisor.name||advisor.email||"Orientador"}</p><p className="text-xs text-ink-soft mt-1">{advisor.email}</p></div><button type="button" disabled={pending} onClick={()=>run(()=>revoke(advisor.user_id))} className="text-sm text-red-700 underline">Retirar acesso</button></div>)}{!advisors.some(item=>item.active)?<p className="text-sm text-ink-soft">Nenhum orientador ativo neste projeto.</p>:null}</div>{invites.some(item=>!item.revoked&&!item.redeemed_at)?<p className="text-xs text-ink-soft mt-4">Há convite pendente até {new Date(invites.find(item=>!item.revoked&&!item.redeemed_at)!.expires_at).toLocaleDateString("pt-BR")}.</p>:null}</section>:null}
      <section className="bg-white border border-line rounded-2xl p-5 mt-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-teal">Revisão colaborativa</p><h2 className="font-display text-2xl mt-2">Comentários e pendências</h2></div><span className="text-sm text-ink-soft">{comments.filter(item=>item.status==="open").length} em aberto</span></div><form onSubmit={event=>{event.preventDefault();run(addComment);}} className="mt-5"><label className="text-sm">Seção<select value={section} onChange={event=>setSection(event.target.value)} className="block w-full sm:w-64 mt-2 border rounded-card p-3">{sections.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm mt-3">Comentário ou solicitação<textarea required minLength={2} maxLength={4000} rows={3} value={comment} onChange={event=>setComment(event.target.value)} className="block w-full mt-2 border rounded-card p-3" placeholder="Registre uma dúvida, orientação ou ajuste necessário."/></label><button disabled={pending} className="bg-teal text-white rounded-card px-4 py-2 mt-3 disabled:opacity-50">Adicionar comentário</button></form><div className="space-y-3 mt-6">{comments.map(item=><article key={item.id} className={`border rounded-card p-4 ${item.status==="resolved"?"bg-paper opacity-70":"bg-white"}`}><div className="flex flex-wrap justify-between gap-2"><span className="text-xs uppercase text-teal">{sections.find(([key])=>key===item.section_key)?.[1]||"Geral"} · {item.author_id===userId?"Você":item.author_id===project.owner_id?"Autor do projeto":"Orientador"}</span><span className="text-xs text-ink-soft">{new Date(item.created_at).toLocaleDateString("pt-BR")}</span></div><p className="text-sm whitespace-pre-wrap mt-3">{item.body}</p><button type="button" disabled={pending} onClick={()=>run(()=>resolve(item.id,item.status!=="resolved"))} className="text-xs text-teal underline mt-3">{item.status==="resolved"?"Reabrir":"Marcar como resolvido"}</button></article>)}{!comments.length?<p className="text-sm text-ink-soft">Nenhum comentário registrado.</p>:null}</div></section>
      <section className="grid lg:grid-cols-2 gap-5 mt-6"><div className="bg-white border border-line rounded-2xl p-5"><h2 className="font-display text-2xl">Reuniões de orientação</h2><form onSubmit={event=>{event.preventDefault();run(addMeeting);}} className="space-y-3 mt-4"><label className="block text-sm">Data<input required type="date" value={meeting.date} onChange={event=>setMeeting(current=>({...current,date:event.target.value}))} className="block w-full border rounded-card p-3 mt-2"/></label><label className="block text-sm">Título<input required minLength={2} maxLength={160} value={meeting.title} onChange={event=>setMeeting(current=>({...current,title:event.target.value}))} className="block w-full border rounded-card p-3 mt-2" placeholder="Ex.: Definição do método"/></label><label className="block text-sm">Decisões e observações<textarea required minLength={2} maxLength={10000} rows={4} value={meeting.notes} onChange={event=>setMeeting(current=>({...current,notes:event.target.value}))} className="block w-full border rounded-card p-3 mt-2"/></label><label className="block text-sm">Próximos passos<textarea maxLength={6000} rows={2} value={meeting.next} onChange={event=>setMeeting(current=>({...current,next:event.target.value}))} className="block w-full border rounded-card p-3 mt-2"/></label><button disabled={pending} className="bg-ink text-white rounded-card px-4 py-2">Salvar reunião</button></form><div className="space-y-3 mt-5">{meetings.map(item=><details key={item.id} className="border border-line rounded-card p-3"><summary className="cursor-pointer text-sm font-medium">{new Date(`${item.occurred_on}T12:00:00Z`).toLocaleDateString("pt-BR",{timeZone:"UTC"})} · {item.title}</summary><p className="text-sm whitespace-pre-wrap mt-3">{item.notes}</p>{item.next_steps?<p className="text-sm text-ink-soft whitespace-pre-wrap mt-3"><strong>Próximos passos:</strong> {item.next_steps}</p>:null}</details>)}</div></div>
      <div className="bg-white border border-line rounded-2xl p-5"><h2 className="font-display text-2xl">Histórico de versões</h2><p className="text-sm text-ink-soft mt-2">Registre marcos antes de mudanças importantes. O conteúdo atual do projeto será copiado para o histórico.</p>{isOwner?<div className="flex gap-2 mt-4"><input maxLength={120} value={versionLabel} onChange={event=>setVersionLabel(event.target.value)} placeholder="Ex.: Antes da reunião de método" className="border rounded-card p-3 flex-1"/><button type="button" disabled={pending||versionLabel.trim().length<2} onClick={()=>run(createVersion)} className="text-teal border rounded-card px-3">Registrar</button></div>:null}<div className="space-y-2 mt-5">{versions.map(item=><label key={item.id} className="flex gap-2 text-sm border border-line rounded-card p-3"><input type="checkbox" checked={compare.includes(item.id)} disabled={!compare.includes(item.id)&&compare.length>=2} onChange={event=>setCompare(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><span><strong>{item.label}</strong><br/><span className="text-xs text-ink-soft">{new Date(item.created_at).toLocaleString("pt-BR")}</span></span></label>)}{!versions.length?<p className="text-sm text-ink-soft">Nenhuma versão registrada.</p>:null}</div>{compare.length===2?<div className="mt-5"><h3 className="font-medium">Alterações entre as versões</h3>{differences.map(item=><details key={item.label} className="border-t border-line py-3"><summary className="text-sm cursor-pointer">{item.label}</summary><div className="grid sm:grid-cols-2 gap-3 mt-3 text-xs"><div className="bg-paper rounded-card p-3 whitespace-pre-wrap"><strong>Anterior</strong><br/>{item.before}</div><div className="bg-teal-soft rounded-card p-3 whitespace-pre-wrap"><strong>Posterior</strong><br/>{item.after}</div></div></details>)}{!differences.length?<p className="text-sm text-ink-soft mt-3">Nenhuma diferença encontrada nos campos principais.</p>:null}</div>:null}</div></section>
    </>}
    {message?<p role="status" className="mt-5 border border-line rounded-card p-4 text-sm">{message}</p>:null}
  </>;
}
