const fs=require('node:fs');const assert=require('node:assert/strict');const {PGlite}=require('@electric-sql/pglite');
const ts=require('typescript');require.extensions['.ts']=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,filename);
const {operationBudget,usageAlert,plans,policy}=require('../lib/access/plans.ts');
assert.equal(operationBudget(4000,6000),10000);assert.throws(()=>operationBudget(5000,6000));assert.throws(()=>operationBudget(-1,5000));assert.throws(()=>operationBudget(2.5,5000));
assert(usageAlert(750,1000).includes('75%'));assert(usageAlert(900,1000).includes('90%'));assert(usageAlert(1000,1000).includes('esgotada'));
(async()=>{
 const db=new PGlite();
 await db.exec(`create role authenticated;create role anon;create role service_role;create schema auth;create schema extensions;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function auth.role() returns text language sql as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
 grant usage on schema auth to authenticated,anon,service_role;grant execute on all functions in schema auth to authenticated,anon,service_role;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz default now(),raw_user_meta_data jsonb default '{}');
 -- Test substitutes only for pgcrypto hashing/random generation, unavailable in WASM.
 create function public.gen_random_bytes(n integer) returns bytea language sql as $$select decode(md5(random()::text),'hex')$$;
 create function public.digest(value text,algorithm text) returns bytea language sql as $$select decode(md5(value),'hex')$$;
 `);
 await db.exec(fs.readFileSync('supabase/scholar_install.sql','utf8').replace('create extension if not exists "pgcrypto";',''));
 await db.exec(fs.readFileSync('supabase/scholar_access.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_productivity.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_library_upgrade.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_library_duplicates.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_search_alerts.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_account_support.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_operations.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_journey_checklist.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/scholar_advising.sql','utf8'));
 const director='11111111-1111-4111-8111-111111111111',resident='22222222-2222-4222-8222-222222222222',outsider='33333333-3333-4333-8333-333333333333';
 await db.query('insert into auth.users(id,email) values($1,$2),($3,$4),($5,$6)',[director,'director@test.local',resident,'resident@test.local',outsider,'outsider@test.local']);
 await db.query("select scholar_bootstrap_platform_admin('director@test.local','owner')");
 const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0])[0];
 const lic=await scalar(`select public.scholar_provision($1,'essential','Programa de teste',1)`,[director]);
 const org=await scalar('select organization_id from scholar_licenses where id=$1',[lic]);
 const as=async(user,role='authenticated')=>{await db.exec('reset role');await db.query(`select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role',$2,false)`,[user,role]);await db.exec('set role '+role);};
 await as(director);
 await assert.rejects(db.query(`select scholar_provision($1)`,[director]),/permission denied/);
 await assert.rejects(db.query(`update scholar_licenses set token_allowance=999999999`),/permission denied/);
 const code=await scalar(`select scholar_create_invite($1,null,null,1)`,[org]);
 await as(resident);await scalar('select scholar_redeem_invite($1)',[code]);await scalar('select scholar_redeem_invite($1)',[code]);
 await as(outsider);
 await assert.rejects(db.query('select scholar_redeem_invite($1)',[code]),/esgotado/);
 await assert.rejects(db.query('select scholar_roster($1)',[org]),/restrito/);
 assert.equal((await db.query('select * from scholar_wallets')).rows.length,0);
 await as(director);
 assert.equal((await db.query('select * from scholar_roster($1)',[org])).rows.length,1);
 const wallet=await scalar('select id from scholar_wallets where user_id=$1',[resident]);
 await assert.rejects(db.query('select scholar_allocate($1,4000000)',[wallet]),/Franquia insuficiente/);
 await db.exec('reset role');
 const project=await scalar(`insert into research_projects(owner_id,title) values($1,'Projeto privado') returning id`,[resident]);
 // Match Supabase's existing grants; the original installer relies on platform defaults.
 await db.exec('grant select,insert,update,delete on research_projects to authenticated;');
 await as(director);assert.equal((await db.query('select id from research_projects where id=$1',[project])).rows.length,0);
 await as(resident);await db.query('select scholar_share_project($1,$2,true)',[project,org]);
 await as(director);assert.equal((await db.query('select id from research_projects where id=$1',[project])).rows.length,1);
 assert.equal((await db.query(`update research_projects set title='Changed' where id=$1 returning id`,[project])).rows.length,0);
 await as(outsider);assert.equal((await db.query('select id from research_projects where id=$1',[project])).rows.length,0);
 await as(resident);
 const supportRequest=await scalar("select scholar_create_support_request('technical','Problema no Radar','A busca não carregou corretamente.')");
 await scalar("select scholar_record_product_event('page_view','radar','/descobrir')");
 const errorEvent=await scalar("select scholar_record_error_event('radar','/descobrir','FETCH_FAILED','Falha controlada no teste')");
 const deletionRequest=await scalar("select scholar_request_account_deletion()");
 await as(outsider);assert.equal((await db.query('select id from scholar_support_requests where id=$1',[supportRequest])).rows.length,0);
 assert.equal((await db.query('select id from scholar_account_requests where id=$1',[deletionRequest])).rows.length,0);
 await assert.rejects(db.query("select scholar_add_support_message($1,'Tentativa indevida')",[supportRequest]),/indisponível/);
 await as(resident);await scalar("select scholar_add_support_message($1,'Informação complementar')",[supportRequest]);
 assert.equal(await scalar("select scholar_cancel_account_deletion($1)",[deletionRequest]),true);
 await as(director);assert.equal(await scalar("select (scholar_operation_summary()->>'users')::int"),3);
 await scalar("select scholar_admin_reply_support($1,'Resposta da equipe','in_progress')",[supportRequest]);
 assert.equal(await scalar("select scholar_admin_resolve_error($1)",[errorEvent]),true);
 await as(outsider);await assert.rejects(db.query("select scholar_operation_summary()"),/Acesso restrito/);
 await as(resident);
 const advisorCode=await scalar('select scholar_create_advisor_invite($1,$2)',[project,'outsider@test.local']);
 await as(outsider);assert.equal(await scalar('select scholar_redeem_advisor_invite($1)',[advisorCode]),project);
 assert.equal((await db.query('select id from research_projects where id=$1',[project])).rows.length,1);
 const comment=await scalar(`insert into scholar_project_comments(project_id,author_id,section_key,body) values($1,$2,'methods','Revisar o método') returning id`,[project,outsider]);
 await assert.rejects(db.query(`select scholar_create_project_version($1,'Versão indevida')`,[project]),/Projeto indisponível/);
 await as(resident);await db.query(`select scholar_resolve_project_comment($1,true)`,[comment]);await db.query(`select scholar_create_project_version($1,'Antes da revisão')`,[project]);
 await as(outsider);assert.equal((await db.query('select id from scholar_project_versions where project_id=$1',[project])).rows.length,1);
 await as(resident);await db.query('select scholar_revoke_advisor($1,$2)',[project,outsider]);
 await as(outsider);assert.equal((await db.query('select id from research_projects where id=$1',[project])).rows.length,0);assert.equal((await db.query('select id from scholar_project_comments where project_id=$1',[project])).rows.length,0);
 await as(resident);await assert.rejects(db.query(`select scholar_reserve(gen_random_uuid(),$1,$2,'ideas','test',10000,null)`,[wallet,resident]),/permission denied/);
 await db.exec('reset role');
 const req='44444444-4444-4444-8444-444444444444';
 await db.query(`select scholar_reserve($1,$2,$3,'ideas','test',10000,null)`,[req,wallet,resident]);
 await db.query(`select scholar_reserve($1,$2,$3,'ideas','test',10000,null)`,[req,wallet,resident]);
 assert.equal(await scalar('select reserved from scholar_wallets where id=$1',[wallet]),policy.maxOperationTokens);
 await assert.rejects(db.query(`select scholar_reserve(gen_random_uuid(),$1,$2,'ideas','test',10000,null)`,[wallet,resident]),/andamento/);
 await assert.rejects(db.query('select scholar_settle($1,5000,6000,0,false,null)',[req]),/Consumo inválido/);
 await db.query('select scholar_settle($1,4000,6000,0.08,false,null)',[req]);
 await db.query('select scholar_settle($1,4000,6000,0.08,false,null)',[req]);
 assert.equal(await scalar('select used from scholar_wallets where id=$1',[wallet]),10000);
 assert.equal(await scalar('select reserved from scholar_wallets where id=$1',[wallet]),0);
 await db.query('select scholar_simulate(gen_random_uuid(),$1,$2,4000,6000,true)',[wallet,resident]);
 assert.equal(await scalar('select used from scholar_wallets where id=$1',[wallet]),10000);
 await as(director);await assert.rejects(db.query('select scholar_allocate($1,9999)',[wallet]),/abaixo/);
 await db.query('select scholar_manage_member($1,$2,false,null)',[org,resident]);
 assert.equal((await db.query('select id from research_projects where id=$1',[project])).rows.length,0);
 await db.exec('reset role');
 await assert.rejects(db.query(`select scholar_reserve(gen_random_uuid(),$1,$2,'ideas','test',10000,null)`,[wallet,resident]),/Vínculo institucional/);
 await as(director);await db.query('select scholar_manage_member($1,$2,true,null)',[org,resident]);
 await db.exec('reset role');
 for(let n=0;n<policy.dailyOperations-2;n++)await db.query('select scholar_simulate(gen_random_uuid(),$1,$2,0,1,false)',[wallet,resident]);
 await assert.rejects(db.query('select scholar_simulate(gen_random_uuid(),$1,$2,0,1,false)',[wallet,resident]),/diário/);
 const personal=await scalar("select scholar_provision($1,'plus')",[resident]);
 assert.equal(await scalar('select token_allowance from scholar_licenses where id=$1',[personal]),plans.plus.tokens);
 await as(resident);assert.equal((await db.query('select id from scholar_wallets')).rows.length,2);
 await db.exec('reset role');
 await db.query("update scholar_licenses set starts_at=now()-interval '2 days',ends_at=now()-interval '1 day' where id=$1",[personal]);
 const personalWallet=await scalar('select id from scholar_wallets where license_id=$1',[personal]);
 await assert.rejects(db.query("select scholar_reserve(gen_random_uuid(),$1,$2,'ideas','test',10000,null)",[personalWallet,resident]),/Franquia indisponível/);
 const topup='55555555-5555-4555-8555-555555555555';
 const before=await scalar('select token_allowance from scholar_licenses where id=$1',[lic]);
 await db.query('select scholar_recharge($1,$2,1000000)',[topup,lic]);
 await db.query('select scholar_recharge($1,$2,1000000)',[topup,lic]);
 assert.equal(await scalar('select token_allowance from scholar_licenses where id=$1',[lic]),before+1000000);
 await assert.rejects(db.query('select scholar_recharge($1,$2,2000000)',[topup,lic]),/já utilizado/);
 await as(resident);await assert.rejects(db.query('select scholar_recharge(gen_random_uuid(),$1,1000000)',[lic]),/permission denied/);
 await assert.rejects(db.query('select scholar_project_owner($1)',[project]),/permission denied/);
 await db.exec('reset role');
 const articleKeep='66666666-6666-4666-8666-666666666666',articleRemove='77777777-7777-4777-8777-777777777777';
 await db.query(`insert into library_articles(id,owner_id,project_id,title,publication_year,authors,publication_types,tags,folder) values
  ($1,$3,$4,'Sono na residência médica',2025,'[]','[]',array['principal'],null),
  ($2,$3,$4,'Sono na residência médica',2025,'[]','[]',array['duplicado'],'Leitura')`,[articleKeep,articleRemove,resident,project]);
 await db.query(`insert into evidence_matrix(owner_id,project_id,article_id,objective,notes) values
  ($1,$2,$3,'Objetivo principal','Nota principal'),($1,$2,$4,null,'Nota complementar')`,[resident,project,articleKeep,articleRemove]);
 await db.query(`insert into library_article_projects(owner_id,article_id,project_id) values($1,$2,$3)`,[resident,articleRemove,project]);
 await as(resident);assert.equal(await scalar('select scholar_merge_library_duplicates($1,$2::uuid[])',[articleKeep,[articleRemove]]),articleKeep);
 await db.exec('reset role');
 assert.equal((await db.query('select id from library_articles where owner_id=$1',[resident])).rows.length,1);
 assert.deepEqual((await db.query('select tags from library_articles where id=$1',[articleKeep])).rows[0].tags.sort(),['duplicado','principal']);
 assert((await db.query('select notes from evidence_matrix where article_id=$1',[articleKeep])).rows[0].notes.includes('Nota complementar'));
 await as(outsider);await assert.rejects(db.query('select scholar_merge_library_duplicates($1,$2::uuid[])',[articleKeep,[articleRemove]]),/principal não encontrado/);
 console.log('PASS: PostgreSQL migrations, RLS isolation, atomic duplicate merge, advisor collaboration, seat limits and protected AI accounting, private support, reversible deletion requests and restricted operations monitoring.');
 await db.close();
})().catch(error=>{console.error(error);process.exitCode=1;});
