import Link from "next/link";
import { redirect } from "next/navigation";
import AdvisingWorkspace,{type Advisor,type AdvisorInvite,type AdvisingComment,type AdvisingMeeting,type AdvisingProject,type AdvisingVersion} from "@/components/advising/advising-workspace";
import { supabaseServer } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
export default async function AdvisingPage({searchParams}:{searchParams:Promise<{projeto?:string}>}){
 const params=await searchParams;const db=await supabaseServer();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login");
 const [ownResult,linksResult]=await Promise.all([db.from("research_projects").select("id,owner_id,title,theme,progress,status").eq("owner_id",user.id).order("updated_at",{ascending:false}),db.from("scholar_project_collaborators").select("project_id").eq("user_id",user.id).eq("active",true)]);
 const ids=Array.from(new Set([...(ownResult.data||[]).map(item=>item.id),...(linksResult.data||[]).map(item=>item.project_id)]));
 let projects=(ownResult.data||[]) as AdvisingProject[];
 if(ids.length){const result=await db.from("research_projects").select("id,owner_id,title,theme,progress,status").in("id",ids);if(!result.error)projects=(result.data||[]) as AdvisingProject[];}
 const project=projects.find(item=>item.id===params.projeto)||projects[0]||null;let comments:AdvisingComment[]=[];let meetings:AdvisingMeeting[]=[];let versions:AdvisingVersion[]=[];let advisors:Advisor[]=[];let invites:AdvisorInvite[]=[];let migrationMissing=Boolean(linksResult.error);
 if(project){const isOwner=project.owner_id===user.id;const results=await Promise.all([db.from("scholar_project_comments").select("id,author_id,section_key,body,status,created_at").eq("project_id",project.id).order("created_at",{ascending:false}),db.from("scholar_advisor_meetings").select("id,created_by,occurred_on,title,notes,next_steps,created_at").eq("project_id",project.id).order("occurred_on",{ascending:false}),db.from("scholar_project_versions").select("id,label,snapshot,created_at").eq("project_id",project.id).order("created_at",{ascending:false}),db.rpc("scholar_project_advisors",{p_project:project.id}),isOwner?db.from("scholar_advisor_invites").select("id,email,expires_at,revoked,redeemed_at").eq("project_id",project.id).order("created_at",{ascending:false}).limit(20):Promise.resolve({data:[],error:null})]);migrationMissing=results.some(result=>Boolean(result.error));comments=(results[0].data||[]) as AdvisingComment[];meetings=(results[1].data||[]) as AdvisingMeeting[];versions=(results[2].data||[]) as AdvisingVersion[];advisors=(results[3].data||[]) as Advisor[];invites=(results[4].data||[]) as AdvisorInvite[];}
 return <div className="max-w-5xl mx-auto"><Link href="/dashboard" className="text-sm text-teal">← Meu espaço</Link><div className="flex flex-wrap justify-between gap-5 items-end mt-5"><div><p className="text-xs uppercase tracking-widest text-teal">Orientação e revisão</p><h1 className="font-display text-4xl md:text-5xl mt-3">Um espaço para evoluir o projeto.</h1><p className="text-ink-soft mt-4 max-w-2xl">Compartilhe somente o projeto escolhido, organize comentários, registre reuniões e preserve versões das decisões científicas.</p></div>{projects.length?<form method="get" className="bg-white border border-line rounded-card p-3"><label className="text-xs text-ink-soft">Projeto<select name="projeto" defaultValue={project?.id} className="block min-w-64 border rounded-card p-2 mt-1">{projects.map(item=><option key={item.id} value={item.id}>{item.title||item.theme||"Projeto sem título"}</option>)}</select></label><button className="text-xs text-teal mt-2">Abrir projeto →</button></form>:null}</div>{migrationMissing?<p role="alert" className="mt-6 bg-amber-50 border border-amber-200 rounded-card p-4 text-sm">O módulo de orientação ainda precisa ser ativado no Supabase com o arquivo scholar_advising.sql.</p>:<AdvisingWorkspace userId={user.id} project={project} comments={comments} meetings={meetings} versions={versions} advisors={advisors} invites={invites} isOwner={project?.owner_id===user.id}/>}</div>;
}
