"use client";
import { useEffect, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase/browser";
type Status="pending"|"current"|"done"|"blocked";type Item={key:string;label:string;description:string;status:Status;note:string;dueDate:string};
const base=[["theme","Tema e recorte","Delimite o problema, a população e o contexto."],["question","Pergunta e objetivos","Alinhe pergunta, objetivo e desfecho principal."],["literature","Revisão da literatura","Registre a estratégia e leia criticamente as referências."],["design","Desenho e métodos","Defina desenho, critérios, variáveis e análise."],["ethics","Ética e autorizações","Mapeie consentimento, proteção de dados e aprovações aplicáveis."],["collection","Coleta ou seleção","Planeje recrutamento, extração ou seleção dos estudos."],["analysis","Análise","Relacione variáveis, objetivos e métodos analíticos."],["writing","Escrita e revisão","Organize resultados, discussão, limitações e referências."],["submission","Entrega ou submissão","Confira normas, documentos e versão final."]] as const;
export default function ProjectJourney({projectId,ownerId}:{projectId:string|null;ownerId:string|null}){const [items,setItems]=useState<Item[]>(base.map(([key,label,description],i)=>({key,label,description,status:i===0?"current":"pending",note:"",dueDate:""})));const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!projectId||!ownerId)return;let active=true;void(async()=>{const {data,error}=await supabaseBrowser().from("scholar_project_milestones").select("milestone_key,status,note,due_date,position").eq("owner_id",ownerId).eq("project_id",projectId).order("position");if(!active)return;if(error){setMessage("Ative a jornada com scholar_productivity.sql.");return;}if(data?.length)setItems(base.map(([key,label,description],i)=>{const saved=data.find(row=>row.milestone_key===key);return{key,label,description,status:(saved?.status||(i===0?"current":"pending")) as Status,note:saved?.note||"",dueDate:saved?.due_date||""};}));})();return()=>{active=false};},[projectId,ownerId]);
 function change(key:string,patch:Partial<Item>){setItems(current=>current.map(item=>item.key===key?{...item,...patch}:item));}
 async function save(){if(!projectId||!ownerId||busy)return;setBusy(true);setMessage("");const rows=items.map((item,index)=>({owner_id:ownerId,project_id:projectId,milestone_key:item.key,status:item.status,note:item.note||null,due_date:item.dueDate||null,position:index+1}));const {error}=await supabaseBrowser().from("scholar_project_milestones").upsert(rows,{onConflict:"owner_id,project_id,milestone_key"});setBusy(false);setMessage(error?"Não foi possível salvar a jornada. Confira a nova migração.":"Jornada salva na sua conta.");}
 const done=items.filter(item=>item.status==="done").length;return <section className="mt-8 bg-white border border-line rounded-2xl p-5 md:p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-teal">Jornada do projeto</p><h3 className="font-display text-2xl mt-2">Do recorte à submissão</h3><p className="text-sm text-ink-soft mt-2">{done} de {items.length} etapas concluídas. O status é seu registro de trabalho, não uma validação científica.</p></div>{projectId?<button type="button" disabled={busy} onClick={save} className="bg-teal text-white px-4 py-2 rounded-card disabled:opacity-50">{busy?"Salvando...":"Salvar jornada"}</button>:<p className="text-sm text-ink-soft">Salve o projeto para registrar as etapas.</p>}</div><div className="mt-5 space-y-3">{items.map((item,index)=><details key={item.key} className="border border-line rounded-card p-4" open={item.status==="current"}><summary className="cursor-pointer"><span className="text-teal text-xs mr-3">{String(index+1).padStart(2,"0")}</span><strong>{item.label}</strong><span className="float-right text-xs text-ink-soft">{{pending:"Pendente",current:"Em andamento",done:"Concluída",blocked:"Bloqueada"}[item.status]}</span></summary><p className="text-sm text-ink-soft mt-3">{item.description}</p><div className="grid md:grid-cols-[180px_170px_1fr] gap-3 mt-4"><label className="text-xs">Status<select value={item.status} onChange={e=>change(item.key,{status:e.target.value as Status})} className="block w-full border rounded-card p-2 mt-1"><option value="pending">Pendente</option><option value="current">Em andamento</option><option value="done">Concluída</option><option value="blocked">Bloqueada</option></select></label><label className="text-xs">Prazo<input type="date" value={item.dueDate} onChange={e=>change(item.key,{dueDate:e.target.value})} className="block w-full border rounded-card p-2 mt-1"/></label><label className="text-xs">Pendência ou próxima ação<input value={item.note} maxLength={2000} onChange={e=>change(item.key,{note:e.target.value})} className="block w-full border rounded-card p-2 mt-1" placeholder="O que precisa acontecer para avançar?"/></label></div></details>)}</div>{message&&<p role="status" className="text-sm text-ink-soft mt-4">{message}</p>}</section>}
