"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { supabaseBrowser } from "@/lib/supabase/browser";
import { plans, money, usageAlert, institutional, policy, licenseStatus, generationStatus } from "@/lib/access/plans";
type License = { id: string; organization_id: string | null; plan: keyof typeof plans; mode: string; status: string; ends_at: string };
type Wallet = { id: string; license_id: string; allowance: number; used: number; reserved: number };
type Usage = { id: string; wallet_id: string; feature: string; mode: string; status: string; input_tokens: number; output_tokens: number; cost_usd: number; created_at: string };
type Review = { usage_id: string; rating: "useful"|"partial"|"not_useful"; feedback: string | null };
export default function LicensePage() {
 const ownerRef=useRef<string|null>(null);
 const [organizations,setOrganizations]=useState<{id:string;name:string}[]>([]);
 const [user, setUser] = useState<string | null>(null); const [licenses,setLicenses]=useState<License[]>([]); const [wallets,setWallets]=useState<Wallet[]>([]);
 const [usage,setUsage]=useState<Usage[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [reviewMessage,setReviewMessage]=useState(""); const [context,setContext]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{ let active=true; const client=supabaseBrowser();
  async function load(){
   try {
    const {data:auth,error:authError}=await client.auth.getUser(); if(authError)throw authError;
    if(!active)return; ownerRef.current=auth.user?.id||null;setUser(ownerRef.current); setLicenses([]);setWallets([]);setUsage([]);setContext("");
    if(!auth.user)return;
    const results=await Promise.all([client.from("scholar_licenses").select("id,organization_id,plan,mode,status,ends_at"),client.from("scholar_wallets").select("id,license_id,allowance,used,reserved").eq("user_id",auth.user.id),client.from("scholar_usage").select("id,wallet_id,feature,mode,status,input_tokens,output_tokens,cost_usd,created_at").eq("user_id",auth.user.id).order("created_at",{ascending:false}).limit(50),client.from("scholar_organizations").select("id,name")]);
    if(!active)return; for(const result of results)if(result.error)throw result.error;
    setOrganizations(results[3].data||[]);setLicenses(results[0].data||[]);const available=results[1].data||[];setWallets(available);setUsage(results[2].data||[]);
    const reviewResult=await client.from("scholar_generation_reviews").select("usage_id,rating,feedback").eq("user_id",auth.user.id);if(!reviewResult.error)setReviews(reviewResult.data||[]);
    let saved="";try{saved=sessionStorage.getItem(`scholar-wallet:${auth.user.id}`)||"";}catch{}
    setContext(available.some(w=>w.id===saved)?saved:available[0]?.id||"");
   }catch{if(active)setError("Não foi possível carregar as licenças. Se este módulo ainda não foi ativado, execute scholar_access.sql no Supabase.");}
   finally{if(active)setLoading(false);}
  }
  void load(); const {data:listener}=client.auth.onAuthStateChange((event,session)=>{if(active && (event === "SIGNED_OUT" || (event === "SIGNED_IN" && ownerRef.current && session?.user.id !== ownerRef.current))){active=false;ownerRef.current=null;setUser(null);setOrganizations([]);setContext("");setLoading(false);setLicenses([]);setWallets([]);setUsage([]);}});
  return()=>{active=false;listener.subscription.unsubscribe();};
 },[]);
 async function review(usageId:string,rating:Review["rating"]){if(!user)return;setReviewMessage("");const {error}=await supabaseBrowser().from("scholar_generation_reviews").upsert({usage_id:usageId,user_id:user,rating},{onConflict:"usage_id"});if(error){setReviewMessage("Execute scholar_productivity.sql para habilitar as avaliações.");return;}setReviews(current=>[...current.filter(item=>item.usage_id!==usageId),{usage_id:usageId,rating,feedback:null}]);setReviewMessage("Avaliação registrada.");}
 const wallet=wallets.find(w=>w.id===context); const license=licenses.find(l=>l.id===wallet?.license_id);
 return <div className="max-w-5xl mx-auto"><p className="text-xs uppercase text-teal">Acesso e assistência</p><h1 className="font-display text-4xl mt-3">Sua licença e franquia</h1><p className="text-ink-soft mt-4">A IA está desligada. Os planos e recargas abaixo são a configuração comercial inicial; compras e cobrança ainda não estão disponíveis.</p>
 <div className="mt-5 flex gap-5 text-sm"><Link href="/residencia" className="text-teal underline">Entrar em uma residência ou abrir coordenação</Link><Link href="/dashboard" className="text-teal underline">Meu espaço</Link></div>
 {loading?<p role="status" className="mt-6">Carregando...</p>:!user?<Link href="/login" className="block mt-6 text-teal underline">Entre para consultar sua licença</Link>:<>
 {error&&<p role="alert" className="mt-6 text-red-700">{error}</p>}
 {!error&&!wallets.length&&<p className="mt-6 bg-paper p-4 border rounded-card">Sua conta ainda não possui uma franquia provisionada. Os recursos atuais sem IA continuam disponíveis.</p>}
 {!!wallets.length&&<section className="mt-6 bg-white border border-line rounded-2xl p-5"><label className="text-sm font-medium">Contexto da assistência<select className="block mt-2 w-full border rounded-card p-3" value={context} onChange={e=>{setContext(e.target.value);try{sessionStorage.setItem(`scholar-wallet:${user}`,e.target.value);}catch{}}}>{wallets.map(w=>{const l=licenses.find(l=>l.id===w.license_id);return <option key={w.id} value={w.id}>{l?.organization_id?organizations.find(o=>o.id===l.organization_id)?.name||"Licença da residência":"Licença individual"} · {l?plans[l.plan].name:"Franquia"} · {l?.mode==="simulation"?"simulação":"licença"}</option>;})}</select></label>
 {wallet&&license&&<><p className="text-sm mt-4">{licenseStatus(license.status)} · válido até {new Date(license.ends_at).toLocaleDateString("pt-BR")} · {license.mode==="simulation"?"Dados de simulação; sem cobrança de API":"IA ainda desligada"}</p><div className="grid sm:grid-cols-3 gap-4 mt-4">{[["Franquia",wallet.allowance],["Utilizado",wallet.used],["Disponível",wallet.allowance-wallet.used-wallet.reserved]].map(([label,value])=><div key={label} className="bg-paper rounded-card p-4"><p className="text-xl">{Number(value).toLocaleString("pt-BR")}</p><p className="text-xs mt-2">{label} · tokens</p></div>)}</div><p role="status" className="mt-4 text-sm text-teal">{usageAlert(wallet.used,wallet.allowance)}</p><p className="text-xs text-ink-soft mt-2">{wallet.reserved.toLocaleString("pt-BR")} tokens reservados para operações em andamento.</p></>}
 <h2 className="font-display text-2xl mt-6">Últimas operações</h2><p className="text-xs mt-2 text-ink-soft">Até 50 operações recentes da sua conta. Falhas podem devolver franquia e ainda registrar custo do provedor.</p><div className="overflow-x-auto mt-3"><table className="w-full text-sm text-left"><thead><tr>{["Data","Ferramenta","Estado","Entrada / saída","Tipo","Avaliação"].map(t=><th key={t} className="p-2" scope="col">{t}</th>)}</tr></thead><tbody>{usage.filter(u=>u.wallet_id===context).map(u=><tr key={u.id} className="border-t"><td className="p-2">{new Date(u.created_at).toLocaleString("pt-BR")}</td><td className="p-2">{({ideas:"Ideias",reading:"Leitura",matrix:"Matriz",refinement:"Refinamento",protocol:"Projeto",writing:"Escrita"} as Record<string,string>)[u.feature]}</td><td className="p-2">{generationStatus(u.status)}</td><td className="p-2">{u.input_tokens} / {u.output_tokens}</td><td className="p-2">{u.mode==="simulation"?"Simulação":"Uso real"}</td><td className="p-2">{u.status==="completed"?<select aria-label="Avaliar resultado" value={reviews.find(item=>item.usage_id===u.id)?.rating||""} onChange={e=>review(u.id,e.target.value as Review["rating"])} className="border rounded-card p-1"><option value="" disabled>Avaliar</option><option value="useful">Útil</option><option value="partial">Parcial</option><option value="not_useful">Não útil</option></select>:"—"}</td></tr>)}</tbody></table></div>{reviewMessage&&<p role="status" className="text-xs text-ink-soft mt-3">{reviewMessage}</p>}{!usage.some(u=>u.wallet_id===context)&&<p className="text-sm mt-3">Nenhuma operação registrada neste contexto.</p>}</section>}
 </>}
 <section className="grid md:grid-cols-3 gap-4 mt-8">{Object.entries(plans).map(([key,p])=><article key={key} className="bg-white border border-line rounded-2xl p-5"><h2 className="font-display text-2xl">{p.name}</h2><p className="text-2xl mt-4">{money(p.annualCents)}<span className="text-sm"> / ano</span></p><p className="text-sm text-ink-soft mt-2">Equivalente aproximado a {money(Math.round(p.annualCents/12))} em 12 parcelas, antes de encargos.</p><p className="text-sm mt-4">{p.tokens/1000000} milhões de tokens anuais entre as ferramentas de IA.</p><p className="text-xs text-teal mt-4">Licença anual · contratação em preparação</p></article>)}</section><p className="text-sm text-ink-soft mt-5">Recarga proposta: {money(policy.rechargeCents)} por 1 milhão de tokens, válida até o fim da licença. Sem renovação automática ativada.</p>
 <section className="mt-6 border border-line rounded-2xl bg-teal-soft p-5"><h2 className="font-display text-2xl">Para programas de residência</h2><p className="text-sm mt-3">Referência inicial: {institutional.seats} vagas Essencial por {money(institutional.annualCents)} ao ano, com coordenação incluída e {institutional.tokens/1000000} milhões de tokens anuais. A franquia pode ser redistribuída entre os residentes.</p><Link href="/residencia" className="inline-block text-sm text-teal underline mt-3">Conhecer o acesso institucional</Link></section>
 </div>;
}
